---
- gather_facts: false
  hosts: localhost
  vars_files:
    - Server_Inventory_hosts.yml
  tasks:
  - name: Create a change ticket in SNOW 
    register: new_change_request
    snow_record:
      data:
        requested_by: "{{item.Requested_by}}"
        cmdb_ci: "{{item.CI}}"
        start_date: "{{item.Release_start_date}}"
        end_date: "{{item.Release_end_date}}"
        short_description: "{{item.Short_Description}}"
        category: "Applications Software"
        assignment_group: "Change Management"
        assigned_to: "Change Manager"
        u_approver: "{{item.Technical_Approver}}"
        type: "Normal"
        description: "{{item.Description}}"
      instance: dev99640
      password: 9tdEV1gUluAW
      state: present
      table: change_request
      username: admin
    with_items:
        - "{{ serverinventory }}"
#    register: new_change_request
#- debug: var=new_change_request.record.number
